### ISSUE TITLE
"TypeError: Cannot read property 'get$kind' of undefined" when debugging Dartino program

### ISSUE THREAD

**Issue by sgjesse** [dartino/atom-dartino#47]
Everything works before turning on debugging.

In the Dartino plug-in I am pointing to a 0.5.0 SDK in `/tmp/dartino-sdk`. In the dartlang SDK I am pointing to the Dart SDK in `/tmp/dartino-sdk/internal/dart-sdk`.
- Add debugging to the launch configuration

```
# Dartino launch configuration for main.dart.
type: dartino
path: main.dart

dartino:
  debug: true
```
- Hit `Run` on the toolbar
- Output in the console

```
Compile and deploy to connected device ...
$ /tmp/dartino-sdk/bin/dartino flash --debugging-mode /Users/sgjesse/dartino-projects/draw/main.dart
Using template settings file '/private/tmp/dartino-sdk/internal/.dartino-settings'
Done building image: /Users/sgjesse/dartino-projects/draw/main.bin
Flashing image: /Users/sgjesse/dartino-projects/draw/main.bin
Done flashing image: /Users/sgjesse/dartino-projects/draw/main.bin
Starting debug session...
$ /tmp/dartino-sdk/bin/dartino debug serve /Users/sgjesse/dartino-projects/draw/main.dart on tty /dev/tty.usbmodem1413
Using template settings file '/private/tmp/dartino-sdk/internal/.dartino-settings'
Attached to /dev/tty.usbmodem1413
localhost:53454
Connecting observatory to application on device...
```

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.29
### Stack Trace

Uncaught NullError: method not found: 'get$kind' on null

```
At /Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:27251

TypeError: Cannot read property 'get$kind' of undefined
    at [object Object].J.get$kind$x (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:78009:40)
    at ObservatoryConnection__registerNewIsolate_closure0.dart.ObservatoryConnection__registerNewIsolate_closure0.call$1 (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:39030:22)
    at _RootZone.dart._RootZone.runUnary$2 (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:49510:20)
    at _FutureListener.dart._FutureListener.handleValue$1 (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:47458:34)
    at _Future__propagateToListeners_handleValueCallback.dart._Future__propagateToListeners_handleValueCallback.call$0 (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:47919:60)
    at [object Object].dart._Future.static._Future__propagateToListeners (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:47778:104)
    at _Future.dart._Future._completeWithValue$1 (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:47639:11)
    at _Future__asyncComplete_closure0.dart._Future__asyncComplete_closure0.call$0 (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:47857:20)
    at [object Object].dart._microtaskLoop (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:46661:27)
    at [object Object].dart._startMicrotaskLoop (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:46667:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:27629:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:29508:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:27242:25)
    at [object Object].dart._callInIsolate (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:26884:28)
    at dart.invokeClosure (/Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:28471:20)
    at /Users/sgjesse/.atom/packages/dartlang/web/entry.dart.js:28492:18
```
### Commands

```
  9x -8:01.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -8:00.1.0 core:move-left (atom-text-editor.editor.is-focused)
 42x -7:59.8.0 core:move-down (atom-text-editor.editor.is-focused)
undefined -7:57.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:58.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -4:45.5.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:44.9.0 core:move-down (atom-text-editor.editor.is-focused)
 11x -4:44.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:40.6.0 core:save (atom-text-editor.editor.is-focused)
     -3:32.6.0 dartino:settings (a.stack-toggle)
     -3:32.5.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -3:19.8.0 dartlang:settings (atom-text-editor#dartino.devicePath.editor.mini.is-focused)
  2x -2:46.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:04.7.0 dartino:settings (a.stack-toggle)
     -1:04.7.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:51.5.0 dartlang:settings (div.package-detail.panels-item)
```
### Config

``` json
{
  "core": {
    "followSymlinks": false,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "dartlang": {
    "sdkLocation": "/tmp/dartino-sdk/internal/dart-sdk"
  }
}
```
### Installed Packages

``` coffee
# User
atom-toolbar, v0.1.6
dartino, v0.0.12
dartlang, v0.6.29
linter, v1.11.14
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by danrubel** [comment]
Fixed.
